// <auto-generated />
using System;
using Fast_Food.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fast_Food.Migrations
{
    [DbContext(typeof(DoAnStoreContext))]
    partial class DoAnStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fast_Food.Models.ChiTietCombo", b =>
                {
                    b.Property<int>("MaCombo")
                        .HasColumnType("int")
                        .HasColumnName("maCombo");

                    b.Property<int>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("maMon");

                    b.HasKey("MaCombo", "MaMon")
                        .HasName("PK__ChiTietC__7D763253D10AE6C3");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietCombo", (string)null);
                });

            modelBuilder.Entity("Fast_Food.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maChiTietHoaDon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietHoaDon"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gia");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("maHoaDon");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("maMon");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.Property<string>("TenMonAn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenMonAn");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("tongTien");

                    b.HasKey("MaChiTietHoaDon")
                        .HasName("PK__chiTietH__7AF692ECEDC9F1F0");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaMon");

                    b.ToTable("chiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("Fast_Food.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maGioHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gia");

                    b.Property<int?>("MaCombo")
                        .HasColumnType("int")
                        .HasColumnName("maCombo");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("maKhachHang");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("maMon");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenSanPham");

                    b.Property<string>("anh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGioHang")
                        .HasName("PK__gioHang__2C76D203DE1916BA");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaMon");

                    b.ToTable("gioHang", (string)null);
                });

            modelBuilder.Entity("Fast_Food.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maHoaDon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<double>("DanhGia")
                        .HasColumnType("float")
                        .HasColumnName("danhGia");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChiGiaoHang");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("maKhachHang");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("maNhanVien");

                    b.Property<int?>("MaVoucher")
                        .HasColumnType("int")
                        .HasColumnName("maVoucher");

                    b.Property<string>("SdtlienHe")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDTLienHe");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianDat");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianKetThuc");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDonHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThaiDonHang");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThaiThanhToan");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__026B4D9AD4E03AD1");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaVoucher");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("Fast_Food.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maKhachHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioiTinh");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenKhachHang");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__0CCB3D49D960668A");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Fast_Food.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maMon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMon"));

                    b.Property<string>("ChiTietFood")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chiTietFood");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinhAnh");

                    b.Property<string>("LoaiSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loaiSanPham");

                    b.Property<DateOnly?>("NgayCapNhat")
                        .HasColumnType("date")
                        .HasColumnName("ngayCapNhat");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date")
                        .HasColumnName("ngayTao");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenMon");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("MaMon")
                        .HasName("PK__MonAn__27547BFA7EFB4EBB");

                    b.ToTable("MonAn", (string)null);
                });

            modelBuilder.Entity("Fast_Food.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maNhanVien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar");

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioiTinh");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenNhanVien");

                    b.Property<int?>("Tuoi")
                        .HasColumnType("int")
                        .HasColumnName("tuoi");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__BDDEF20DF78D35B1");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Fast_Food.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maTaiKhoan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("LoaiTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loaiTaiKhoan");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("maKhachHang");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("matKhau");

                    b.Property<string>("TenTk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenTK");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__taiKhoan__8FFF6A9D576AD94F");

                    b.HasIndex(new[] { "MaKhachHang" }, "UQ_KhachHang")
                        .IsUnique()
                        .HasFilter("[maKhachHang] IS NOT NULL");

                    b.HasIndex(new[] { "MaNhanVien" }, "UQ_NhanVien")
                        .IsUnique()
                        .HasFilter("[maNhanVien] IS NOT NULL");

                    b.ToTable("taiKhoan", (string)null);
                });

            modelBuilder.Entity("Fast_Food.Models.Voucher", b =>
                {
                    b.Property<int>("MaVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maVoucher");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVoucher"));

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngayBatDau");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngayKetThuc");

                    b.Property<int>("SoLanSuDungHienTai")
                        .HasColumnType("int")
                        .HasColumnName("soLanSuDungHienTai");

                    b.Property<int>("SoLanSuDungToiDa")
                        .HasColumnType("int")
                        .HasColumnName("soLanSuDungToiDa");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("soTienGiam");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("MaVoucher")
                        .HasName("PK__Voucher__E335C400381BF7D9");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("Fast_Food.Models.ChiTietCombo", b =>
                {
                    b.HasOne("Fast_Food.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietCombos")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietCo__maMon__2C3393D0");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("Fast_Food.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Fast_Food.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__chiTietHo__maHoa__35BCFE0A");

                    b.HasOne("Fast_Food.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaMon")
                        .HasConstraintName("FK__chiTietHo__maMon__34C8D9D1");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("Fast_Food.Models.GioHang", b =>
                {
                    b.HasOne("Fast_Food.Models.MonAn", "MaComboNavigation")
                        .WithMany("GioHangMaComboNavigations")
                        .HasForeignKey("MaCombo")
                        .HasConstraintName("FK__gioHang__maCombo__412EB0B6");

                    b.HasOne("Fast_Food.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK__gioHang__maKhach__3F466844");

                    b.HasOne("Fast_Food.Models.MonAn", "MaMonNavigation")
                        .WithMany("GioHangMaMonNavigations")
                        .HasForeignKey("MaMon")
                        .HasConstraintName("FK__gioHang__maMon__403A8C7D");

                    b.Navigation("MaComboNavigation");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("Fast_Food.Models.HoaDon", b =>
                {
                    b.HasOne("Fast_Food.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__maKhachH__300424B4");

                    b.HasOne("Fast_Food.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__HoaDon__maNhanVi__30F848ED");

                    b.HasOne("Fast_Food.Models.Voucher", "MaVoucherNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaVoucher")
                        .HasConstraintName("FK__HoaDon__maVouche__31EC6D26");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaVoucherNavigation");
                });

            modelBuilder.Entity("Fast_Food.Models.TaiKhoan", b =>
                {
                    b.HasOne("Fast_Food.Models.KhachHang", "MaKhachHangNavigation")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("Fast_Food.Models.TaiKhoan", "MaKhachHang")
                        .HasConstraintName("FK__taiKhoan__maKhac__3B75D760");

                    b.HasOne("Fast_Food.Models.NhanVien", "MaNhanVienNavigation")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("Fast_Food.Models.TaiKhoan", "MaNhanVien")
                        .HasConstraintName("FK__taiKhoan__maNhan__3C69FB99");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("Fast_Food.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Fast_Food.Models.KhachHang", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Fast_Food.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietCombos");

                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("GioHangMaComboNavigations");

                    b.Navigation("GioHangMaMonNavigations");
                });

            modelBuilder.Entity("Fast_Food.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Fast_Food.Models.Voucher", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
